version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ".devcontainer/docker/python/Dockerfile"
    working_dir: "/app"
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./:/app
    command: >
      sh -c "python -m http.server 8000;"
    depends_on:
      - react

  react:
    build: 
      context: .
      dockerfile: ".devcontainer/docker/node/Dockerfile"
    working_dir: "/app"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"